### ISSUE TITLE
CRS and axis order: B13346_05_09-reprojection.py

### ISSUE THREAD

**Issue by sledgesickle** [PacktPublishing/Learning-Geospatial-Analysis-with-Python-Third-Edition#1]
Running B13346_05_09-reprojection.py reprojects the NYC_MUSEMS_LAMBERT shapefile to Antartica using Python 3.9 and the latest GDAL 3.x library. West becomes South. North becomes East. The problem is "explained" in the following GDAL Tutorial,
  
https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order

I added the following statement to the referenced python script correct the reprojection. 

tgt_spatRef.SetAxisMappingStrategy(0)

The default value is 1 for OAMS_AUTHORITY_COMPLIANT which results in the axis order change. 
0 corresponds to OAMS_TRADITIONAL_GIS_ORDER which produces the desired result.

The source shapefile NYC_MUSEMS_LAMBERT Authority value is blank, the WKID=0. Seems odd you would need to tell GDAL to treat a file like a duck if it quacks like a duck.

**Comment by GeospatialPython** [comment]
Good catch. I read about that change a couple of weeks ago and didn't think about that impact.  The master branch has been updated.
