### ISSUE TITLE
The result of clip a raster image using a shapefile is WRONG.

### ISSUE THREAD

**Issue by ZaneLau-Info** [PacktPublishing/Learning-Geospatial-Analysis-with-Python-Third-Edition#2]
When you overlay the clip result with the stretched image, you will find they cann't fit together. I cann't find the error in B13346_06_04-clip.py.

**Comment by GeospatialPython** [comment]
What version of python and gdal are you using?

**Comment by saurabhk710** [comment]
HIi @ZaneLau-SpatialInfo can you please reply to @GeospatialPython so that he can help you ?
